const playerOne = [
  "Monkey D. Luffy",
  "Roronoa Zoro",
  "Nami",
  "Usopp",
  "Sanji",
  "Tony Tony Chopper",
  "Nico Robin",
  "Franky",
  "Brook",
  "Jimbei",
];
const fightingWord = [
  "pop",
  "rout",
  "thud",
  "lean on",
  "boot",
  "bop",
  "take off",
  "raid",
  "spank",
  "pound",
  "extort",
  "rectify",
  "destroy",
  "engage",
  "amend",
  "drive",
  "squeeze",
  "cook",
  "advance",
  "bring down",
  "clout",
  "whip",
  "outmaneuver",
  "buck",
  "annex",
  "punish",
  "raze",
  "prevail",
  "blast",
  "hurdle",
  "bully",
  "assassinate",
  "scatter",
  "outplay",
  "whale",
  "jolt",
  "bounce",
  "slaughter",
  "ambush",
  "larrup",
  "drown",
  "shove",
  "clip",
];
const playerTwo = [
  "Lee",
  "Guy",
  "Gaara",
  "Hinata",
  "Sakura",
  "Kakashi",
  "Naruto",
  "Iruka",
  "Sasuke",
  "Itachi",
  "Shikamaru",
  "Shino",
  "Neji",
];

firstWord = playerOne[Math.floor(Math.random() * playerOne.length)];
secondWord = fightingWord[Math.floor(Math.random() * fightingWord.length)];
thirdWord = playerTwo[Math.floor(Math.random() * playerTwo.length)];

console.log(`${firstWord} wants to ${secondWord} ${thirdWord}.`);
