const first = [
  "Monkey D. Luffy",
  "Roronoa Zoro",
  "Nami",
  "Usopp",
  "Sanji",
  "Tony Tony Chopper",
  "Nico Robin",
  "Franky",
  "Brook",
  "Jimbei",
];
const second = [
  "pop",
  "rout",
  "thud",
  "lean on",
  "boot",
  "bop",
  "take off",
  "raid",
  "spank",
  "pound",
  "extort",
  "rectify",
  "destroy",
  "engage",
  "amend",
  "drive",
  "squeeze",
  "cook",
  "advance",
  "bring down",
  "clout",
  "whip",
  "outmaneuver",
  "buck",
  "annex",
  "punish",
  "raze",
  "prevail",
  "blast",
  "hurdle",
  "bully",
  "assassinate",
  "scatter",
  "outplay",
  "whale",
  "jolt",
  "bounce",
  "slaughter",
  "ambush",
  "larrup",
  "drown",
  "shove",
  "clip",
];
const third = [
  "Lee",
  "Guy",
  "Gaara",
  "Hinata",
  "Sakura",
  "Kakashi",
  "Naruto",
  "Iruka",
  "Sasuke",
  "Itachi",
  "Shikamaru",
  "Shino",
  "Neji",
];

firstWord = first[Math.floor(Math.random() * first.length)];
secondWord = second[Math.floor(Math.random() * second.length)];
thirdWord = third[Math.floor(Math.random() * third.length)];

console.log(firstWord + " wants to " + secondWord + " " + thirdWord + ".");
